[package]
name = "qadapt-broken-tests"
version = "0.0.0"
authors = ["The SiO4 Project Developers <https://gitlab.com/sio4>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
qadapt = "*"
